const entries = [
    {
      uuid: 0,
      date: "2022-12-25",
      type: "spend",
      amount: 12.99,
      description: "Coffee Shop",
      note: "Bought a latte",
    },
    {
      uuid: 1,
      date: "2022-12-20",
      type: "spend",
      amount: 45.67,
      description: "Grocery Store",
      note: "Bought food for the week",
    },
    {
      uuid: 2,
      date: "2022-12-15",
      type: "deposit",
      amount: 2000,
      description: "Transfer",
      note: "Transferred money from savings",
    },
    {
      uuid: 3,
      date: "2022-12-10",
      type: "spend",
      amount: 8.99,
      description: "Gas Station",
      note: "Filled up the tank",
    },
    {
      uuid: 4,
      date: "2022-12-05",
      type: "spend",
      amount: 23.45,
      description: "Movie Theater",
      note: "Saw a new release",
    },
    {
      uuid: 5,
      date: "2022-12-01",
      type: "spend",
      amount: 9.99,
      description: "Fast Food Restaurant",
      note: "Got a burger and fries",
    },
    {
      uuid: 6,
      date: "2022-11-25",
      type: "deposit",
      amount: 500,
      description: "Payday",
      note: "Received salary",
    },
    {
      uuid: 7,
      date: "2023-03-20",
      type: "spend",
      amount: 35.2,
      description: "Clothing Store",
      note: "Bought a new shirt",
    },
    {
      uuid: 8,
      date: "2023-03-23",
      type: "spend",
      amount: 15.5,
      description: "Restaurant",
      note: "Had lunch with friends",
    },
    {
      uuid: 9,
      date: "2023-03-24",
      type: "deposit",
      amount: 1000,
      description: "Payday",
      note: "Received salary",
    },
    {
      uuid: 10,
      date: "2023-03-20",
      type: "spend",
      amount: 50.0,
      description: "Sporting Goods Store",
      note: "Bought a new pair of running shoes",
    },
    {
      uuid: 11,
      date: "2023-03-21",
      type: "spend",
      amount: 27.99,
      description: "Bookstore",
      note: "Bought a new novel",
    },
    {
      uuid: 12,
      date: "2023-03-22",
      type: "deposit",
      amount: 500,
      description: "Transfer",
      note: "Transferred money from checking",
    },
    {
      uuid: 13,
      date: "2023-03-23",
      type: "spend",
      amount: 12.0,
      description: "Fast Food Restaurant",
      note: "Got a combo meal",
    },
    {
      uuid: 14,
      date: "2023-03-24",
      type: "spend",
      amount: 75.0,
      description: "Clothing Store",
      note: "Bought a new dress",
    },
    {
      uuid: 15,
      date: "2023-03-25",
      type: "spend",
      amount: 35.0,
      description: "Electronics Store",
      note: "Bought a new phone charger",
    },
    {
      uuid: 16,
      date: "2023-03-26",
      type: "deposit",
      amount: 1500,
      description: "Payday",
      note: "Received salary",
    },
    {
      uuid: 17,
      date: "2023-03-27",
      type: "spend",
      amount: 19.99,
      description: "Fast Food Restaurant",
      note: "Got a burger, fries, and a drink",
    },
    {
      uuid: 18,
      date: "2023-03-28",
      type: "spend",
      amount: 89.99,
      description: "Electronics Store",
      note: "Bought a new pair of headphones",
    },
    {
      uuid: 19,
      date: "2023-03-29",
      type: "spend",
      amount: 22.5,
      description: "Gas Station",
      note: "Filled up the tank",
    },
    {
      uuid: 20,
      date: "2023-03-30",
      type: "spend",
      amount: 15.0,
      description: "Coffee Shop",
      note: "Bought a latte",
    },
    {
      uuid: 21,
      date: "2023-03-31",
      type: "deposit",
      amount: 200,
      description: "Refund",
      note: "Received a refund for a returned item",
    },
    {
      uuid: 22,
      date: "2023-04-01",
      type: "spend",
      amount: 59.99,
      description: "Clothing Store",
      note: "Bought a new outfit",
    },
    {
      uuid: 23,
      date: "2023-04-02",
      type: "spend",
      amount: 8.5,
      description: "Fast Food Restaurant",
      note: "Got a snack",
    },
    {
      uuid: 24,
      date: "2023-04-03",
      type: "spend",
      amount: 25.0,
      description: "Sporting Goods Store",
      note: "Bought a new soccer ball",
    },
    {
      uuid: 25,
      date: "2023-04-04",
      type: "spend",
      amount: 17.99,
      description: "Bookstore",
      note: "Bought a new cookbook",
    },
  ]

export default entries;